### PR TITLE
support for creating intermediate directories with SVN tagging

### PR DESCRIPTION
**Pull request by kmoens**
Currently we make use of a directory structure within our SVN 'tags' directory. Hereby we create some subdirectories based on major and major.minor versions of our tags. We can now achieve this behavior with the tagTemplate option (at least partly). 

Some examples:
```
/tags/1/1.20/1.20.1.5
```

Corresponding tag template:
```
'${ version.tokenize(".")[0] }/${ version.tokenize(".")[0] + "." + version.tokenize(".")[1] }/${version}'
```

The caveat is that SVN does not create the intermediate directories by default, therefore we need the `--parents` option, which is where this pull request is for.

### CODE REVIEW

**Comment by danez** [comment]
What happens currently when you try to use your tag-template? It fails?
Anyway looks good, I don't think this harms something.

**Comment by kmoens** [comment]
Idd, currently it fails, with a message like this:

[2015-06-11 10:40:15.101]  Running [svn, --non-interactive, --no-auth-cache, --username, jenkins, --password, ****, cp, svn://ontw-java-01.int.cipal.be:8082/cipalcommon/CipalAntTasks/trunk/CipalAntTasks@12165, svn://ontw-java-01.int.cipal.be:8082/cipalcommon/CipalAntTasks/tags/1/1.02/1.02.1.00, -m, Kenny Moens (kmo) - creating tag -  '1/1.02/1.02.1.00'.] produced an error: [svn: E160013: File not found: transaction '12165-9gf', path '/CipalAntTasks/tags/1/1.02/1.02.1.00']

The reason for this is that the intermediate path, and more specifically the "1.02" directory, does not exist yet.

**Comment by danez** [comment]
Thanks for your contribution.
If you want you can try the SNAPSHOT of the next version and see if it works.

```
buildscript {
  repositories {
    maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
  }

  dependencies {
    classpath 'net.researchgate:gradle-release:2.1.2-SNAPSHOT'
  }
}
```

**Comment by kmoens** [comment]
Thanks for the quick merge. I just tried the SNAPSHOT and can confirm it works.

**Pull request merged**
