### PR TITLE
Proposed new feature to force push when committing just the version file

### PR DESCRIPTION
**Pull request by gary-kupferle**

### CODE REVIEW

**Comment by danez** [comment]
What is the usecase for force pushing the version file? Isn't that very dangerous?

**Comment by gary-kupferle** [comment]
We may have found another way to solve our particular problem, but let me describe our use case. I do not think it is dangerous in what I describe, but I am open to why you think so.

Our use case was two potential thing occurring while an application build runs on a CI server. Our app build has many functional tests and is a Grails app, so that build can take a while (20 minutes as we do not currently runs suites of functional tests in parallel -- that is on our backlog). The two two things that could occur are/were:
1. Developer checks in new code during the build. A regular push fails because the local repo for the CI build is not up-to-date.
2. Our application has a depends on set of libraries (jar files) that we manage through the use of https://github.com/nebula-plugins/gradle-dependency-lock-plugin. The set of jars may trigger builds by updating the "lock file" of the application while a CI build is running, causing the push to fail.

In either case, the CI build has at the point of the release plugin updating the version and attempting to push, completed the build, run all unit and functional tests as well as code quality checks. When the build is successful, it really should be valid to push the updated version.

We have found other potential solutions to this problem. I would still be interested in your thoughts for putting this into the Gradle release plugin. I am actively trying to improve our build system.

Thanks,
Gary

**Comment by danez** [comment]
I see the problem you are having, but I still see automated force pushing as very dangerous. The reason is, that all commits, which happened during build start and build end are overwritten on the server and potentially lost, because you are completely overwriting the git history on the server. Sure other people could then do `git pull --rebase` probably, but I see a lot of potential to mess up the tree.

But I also think it's probably not the plugin to decide what workflow to use and as there are a lot of requests coming in to change params of git operations, maybe I should think of making options that allow to add custom params to git commands.

**Comment by gary-kupferle** [comment]
Now I see your objection. My GitFu (Git expertise) is lacking here. My intent was certainly NOT to overwrite history.

One part of the solution we are currently vetting out is at the end of the process doing a `git pull` (merging changes to the local repo where CI build is running), then a push with the new version number (without a force). We are having some issues getting that to work, but it does avoid re-writing history.

I'll abandon this pull request per your feedback if that's the way you want to handle this.

I created issue #175 (https://github.com/researchgate/gradle-release/issues/175) on this topic as well. I'm still learning how people like to manage things in GitHub. Please let me know if I should do something to close/reject that since I started it. I'm happy to clean up both he PR and issue, just let me know your preference on this project.

Thanks,
Gary

**Comment by danez** [comment]
I was thinking about how one could solve this problem. Even if you use pull/push after the whole build you might endup publishing stuff, that you haven't build and/or tested. This is tricky...

**Comment by gary-kupferle** [comment]
It is a bit tricky, but if you finish tagging and publishing of what was built on CI and then pull/push it should be OK. The publish would still be from the state of the local repo which was verified by the tests. Pull/push AFTER the publish/tag/etc. effectively is only pushing the new version number, correct?

**Comment by Hillkorn** [comment]
Hey, sorry for the late answer. Not sure if this topic is still of interest for you.
But if you do a force push it doesn't just push the version instead it forces the local git history to be the remove history. That means that all commits that have been pushed in between from other sources will disappear. They still exists in the source until it does a pull. In this case every commit the source did will disappear. If you don't have those commits in a seperate branch or the hashes saved somewhere i don't know if it's possible to get those back.
I hope it's understandable.

Cause of this problems that it can create i don't think it's a good idea at all to integrate this functionality.

**Comment by Hillkorn** [comment]
Will close it for not, cause of thoughts written in the last comment.

**Pull request closed without merging**
