### PR TITLE
Added custom Android build supporting flavors

### PR DESCRIPTION
**Pull request by ntarocco**
I am using the gradle-release plugin for Android, but I had to modify the build tasks.

Executing ./gradlew build will build all the possible build types.
In my project, I am using the Android flavors which will generate n possible build type, based on the flavor dimensions.
With this PR, I can pass a list of flavors to build.

### CODE REVIEW

**Comment by danez** [comment]
Thanks for your contribution.
Wouldn't it be enough to just have a new configuration option which is an array of build-tasks (default to ['build']) or do I miss something?
I would like to make this as generic as possible.

**Comment by ntarocco** [comment]
If I understand correctly your point, you would like to pass as param the list of task names for the build?
For me it works, in my opinion it was more clear to have a "custom class" for Android, but if you prefer, I can pass an optional param "buildTaskNames" or similar...

The only risk I see is that the task named "build" is hiding the assemble and test tasks.
By passing the list of tasks, someone can forget the test task for example...

**Comment by danez** [comment]
But If you are already in the need of changing the build task, then you are probably aware that you want to assemble and test on release. I can see that having a helper that generates the tasks for you is very convenient, but this plugin itself should stay independent of the used target, libraries or other plugins one uses. 
I think you probably could still create a helper in your ```build.gradle``` or as a separate library that helps you creating the assemble and test tasks. Something like:
```groovy
release {
    buildTasks = AndroidHelper.getTaskNamesForFlavors(['android1', 'android2'])
}
```

**Comment by ntarocco** [comment]
I have updated the PR, now I am passing just an optional list of tasks.

**Comment by danez** [comment]
thanks

**Comment by ntarocco** [comment]
Hey @danez, any idea when the next release with this PR merged will happen?

Thanks!

**Comment by danez** [comment]
I would want to also get #116 merged and tested in the next release. And I think I can get it released till next Monday.

Meanwhile you might want to use the latest snapshot taken from master.

```groovy
buildscript {
  repositories {
    maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
  }

  dependencies {
    classpath 'net.researchgate:gradle-release:2.2.0-SNAPSHOT'
  }
}
```

**Comment by ntarocco** [comment]
Thank you for your email.
I wrote you another comment because one commit has broken my PR.

Thanks,
Nicola

**Comment by danez** [comment]
I released 2.2 on the weekend. Let me know if you have any problems.

**Pull request merged**
