### PR TITLE
Add configuration to remove hyphen from tag

### PR DESCRIPTION
**Pull request by dlvenable**
The current behavior of this plugin is to include a hyphen between the tagPrefix and the version. We prefer to not have that hyphen to keep consistency among all of our projects.

These commits add a new configuration option - includeHyphenInTag. The default value is true, which is how the plugin works now. The value may be set to false and there will be no hyphen between the tagPrefix and the version.

I chose to make this a configuration option so that existing users of the plugin have the same behavior as before.

### CODE REVIEW

**Comment by danez** [comment]
Thanks for the pull request, I'm currently trying to figure out some other issues. Will have a look shortly.

**Comment by townsfolk** [comment]
I never quite liked the way I did the prefix thing. I think it would be better to have the hyphen as part of the tagPrefix - so the plugin doesn't assume anything. This would be a breaking change though...

**Comment by dlvenable** [comment]
I do believe that removing the hyphen from the code would be better. But, as I've not worked on this project before I assumed you either had a specific reason for it, or did not want a breaking change.

**Comment by danez** [comment]
A good idea might be to leave the decision of how the tag should look like completely to the user of the plugin. This could be done in a similar way as it is done with the versionPatterns.
This pattern could be configured like "prefix-${version}" or "${version}-${projectname}", whatever one wants. I think it would be also possible to implement this change as a new option, without breaking backwards compatibility, so that the old configuration still works.

**Comment by dlvenable** [comment]
Here is what I understand you are suggesting:
- Add a new property called versionPattern
- If versionPattern is set, then use that version pattern.
- If versionPattern is not set, then use the existing tag prefix with the hyphen.

I think this is a great approach.

**Comment by swpalmer** [comment]
Or slightly simplified: just have the default value of versionPattern be "{prefix}-"

Scott

**Comment by marshallpierce** [comment]
I was also surprised by this the first time I used the plugin. Is the "${prefix}-" default template the way forward?

**Comment by danez** [comment]
I added my solution in #96. What do you think about that? Will that work for you?

**Comment by dlvenable** [comment]
Thanks @danez for #96. I've not tried it, but taking a look at how it works, this seems a great approach.

**Pull request closed without merging**
